feat: adding maven central publication
* change log for snapshot is not full by default
* added maven central mandatory info
* native installer enable for snapshot
* added devfiles
* fixed java doc error
* missing jreleaser version
* refactor: workflow jpackage to mvnw instead of jreleaser
* fix: alpine was not uploaded
* moving from cli to maven jreleaser
* fix: jdk.dynalink missing for Rhino
* added tag for brew

diff --git a/.github/workflows/release-assemble-jpackage.yml b/.github/workflows/release-assemble-jpackage.yml
--- a/.github/workflows/release-assemble-jpackage.yml
+++ b/.github/workflows/release-assemble-jpackage.yml
@@ -18,6 +18,11 @@ on:
           - windows-latest
           - macos-latest
           - all
+      tag:
+        description: 'Tag to checkout (vx.x.x or early-access)'
+        required: true
+        type: string
+        default: 'early-access'
   workflow_call:
     # ! input have to be duplicated with workflow_dispatch
     # Limitations of GitHub: https://github.com/orgs/community/discussions/39357
@@ -27,6 +32,10 @@ on:
         required: true
         default: windows-latest
         type: string
+      tag:
+        description: 'Tag to checkout (vx.x.x or early-access)'
+        required: true
+        type: string
 
 # Constant for entire workflow
 env:
@@ -34,14 +43,19 @@ env:
   JRELEASER_JPACKAGE_ASSEMBLY_NAME: 'doc-exec-installer'
   JRELEASER_JLINK_ASSEMBLY_NAME: 'doc-exec-jre'
   JRELEASER_JAVA_ARCHIVE_ASSEMBLY_NAME: 'doc-exec-nojre'
-  JRELEASER_OUT_DIRECTORY: 'target'
+  BUILD_DIRECTORY: 'target'
   WORKFLOW_ID: 'release-assemble-jpackage' # the workflow name without extension
+  # Even if we can get it from the pom, it's fix, and we win a couple of second with help:evaluate
+  ARTIFACT_ID: combostrap-doc-exec
+  SNAPSHOT_TAG: early-access
 
 jobs:
 
   # Jlink archive used by Jpackage are build and tested on a Linux OS
   assemble-archive:
     uses: ./.github/workflows/release-assemble-archive.yml
+    with:
+      tag: ${{ inputs.tag }}
 
   # The name is used as path in GitHub
   # So we get from a release run: release-assemble / assemble-archive
@@ -61,10 +75,10 @@ jobs:
     steps:
 
       # Checkout
-      - name: Git Checkout
+      - name: Git Checkout ${{ inputs.tag }}
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.ref }}
+          ref: ${{ inputs.tag }}
           fetch-depth: 0
 
       # Cache to not download the maven dependency between matrix run
@@ -77,24 +91,6 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-maven-
 
-
-      - name: Utility installation Windows
-        if: runner.os == 'Windows'
-        # silent = no GUI windows, progress bars, or installer dialogs
-        # force = to avoid the error: `Found an existing package already installed`
-        # https://learn.microsoft.com/en-us/windows/package-manager/winget/install
-        # Yq to query xml
-        run: winget install -e --id=MikeFarah.yq -v 4.48.1 --silent --accept-source-agreements --accept-package-agreements --force
-
-      # Homebrew is installed but not in the path
-      # https://github.com/actions/runner-images/issues/6283
-      - name: Homebrew Set up
-        if: runner.os != 'Windows'
-        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
-      - name: Homebrew Utility installation Linux/Macos
-        if: runner.os != 'Windows'
-        run: brew install yq
-
       # Extract Properties from pom.xml
       - name: Properties
         id: props
@@ -103,45 +99,31 @@ jobs:
           
           set -TCEeuo pipefail
           
-          # Detect OS and set yq command
-          # to resolve `yq: command not found`
-          if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
-            YQ_CMD="$LOCALAPPDATA/Microsoft/WinGet/Links/yq.exe"
-          else
-            YQ_CMD="yq"
+          # Project version and tag
+          # Why not yq even if mvnw help:evaluate is fucking slow
+          # Because if yq install failed (ie Download request status is not success)
+          # It's more slow as we need to restart the whole archive flow
+          PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
+          PROJECT_TAG="v$PROJECT_VERSION"
+          if [[ "$PROJECT_VERSION" =~ .*-SNAPSHOT ]]; then
+            PROJECT_VERSION=${{env.SNAPSHOT_TAG}}
+            PROJECT_TAG=${{env.SNAPSHOT_TAG}}
           fi
-          
-          # Generate the effective pom
-          POM_EFFECTIVE="${{runner.temp}}/pom-effective.xml"
-          ./mvnw help:effective-pom "-Doutput=$POM_EFFECTIVE"
-          
-          # Why yq because mvnw help:evaluate is fucking slow
-          PROJECT_VERSION=$($YQ_CMD --exit-status '.project.version' "$POM_EFFECTIVE")
           echo "project_version=$PROJECT_VERSION" >> $GITHUB_OUTPUT
           
-          # Project effective version
-          case "$PROJECT_VERSION" in
-            *-SNAPSHOT)
-              PROJECT_EFFECTIVE_VERSION="$(yq --exit-status '.project.snapshot.label' jreleaser.yml)"
-              ;;
-            *)
-              PROJECT_EFFECTIVE_VERSION="$PROJECT_VERSION"
-              ;;
-          esac
-          echo "project_effective_version=${PROJECT_EFFECTIVE_VERSION}" >> $GITHUB_OUTPUT
+          # Check
+          TAG="${{ inputs.tag }}"
+          if [ "$PROJECT_TAG" != "$TAG" ]; then
+            echo "Derived Tag from pom.xml ($PROJECT_TAG) is not the same as the workflow tag $TAG"
+            exit 1
+          fi
           
-          ARTIFACT_ID=$($YQ_CMD --exit-status '.project.artifactId' "$POM_EFFECTIVE")
-          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT
-          
-          JDK_VERSION=$($YQ_CMD --exit-status '.project.properties."jdk.version"' "$POM_EFFECTIVE")
+          JDK_VERSION=$(./mvnw help:evaluate -Dexpression=jdk.version -q -DforceStdout)
           echo "jdk_version=$JDK_VERSION" >> $GITHUB_OUTPUT
           
-          JDK_DISTRO=$($YQ_CMD --exit-status '.project.properties."jdk.distribution"' "$POM_EFFECTIVE")
+          JDK_DISTRO=$(./mvnw help:evaluate -Dexpression=jdk.distribution -q -DforceStdout)
           echo "jdk_distro=$JDK_DISTRO" >> $GITHUB_OUTPUT
           
-          JDK_DOWNLOAD_DIRECTORY=$($YQ_CMD --exit-status '.project.properties."jdk.download-directory"' "$POM_EFFECTIVE")
-          echo "jdk_download_directory=$JDK_DOWNLOAD_DIRECTORY" >> $GITHUB_OUTPUT
-                    
           # Runner arch normalization
           # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#runner-context
           case "${{ runner.arch }}" in
@@ -201,11 +183,11 @@ jobs:
       - name: Maven Setup JDKs
         # The shell is bash on Linux and Powershell in Windows
         # The quotes are mandatory for Windows otherwise it will see -Djdk.name=xxx as powershell parameter
-        run: ./mvnw --no-transfer-progress --batch-mode --file pom.xml -Pjdks "-Djdk.name=${{ steps.props.outputs.platform_artifact }}"
+        run: ./mvnw --no-transfer-progress --batch-mode -Pjdks "-Djdk.name=${{ steps.props.outputs.platform_artifact }}"
 
       # Build jar, still needed by Jpackage even with the jlink runtime ???
       - name: Maven Build Jar
-        run: ./mvnw --no-transfer-progress --batch-mode --file pom.xml -DskipTests package
+        run: ./mvnw --no-transfer-progress --batch-mode -DskipTests package
 
       # Wix v3 is needed by Jpackage
       - name: Winget Install WiX v3
@@ -222,32 +204,23 @@ jobs:
         with:
           pattern: jlink-${{ steps.props.outputs.project_version }}-${{ steps.props.outputs.os_artifact }}
           merge-multiple: true # download them to the same directory
-          path: ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JLINK_ASSEMBLY_NAME}}/jlink
+          path: ${{env.BUILD_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JLINK_ASSEMBLY_NAME}}/jlink
 
       - name: Expand jlink
         shell: bash
         run: |
-          cd ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JLINK_ASSEMBLY_NAME}}/jlink
+          cd ${{env.BUILD_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JLINK_ASSEMBLY_NAME}}/jlink
           ls -l
-          unzip -q -d work-${{ steps.props.outputs.platform_jreleaser }} ${{ steps.props.outputs.artifact_id }}-${{ steps.props.outputs.project_effective_version }}-jre-${{ steps.props.outputs.platform_artifact }}.zip
+          unzip -q -d work-${{ steps.props.outputs.platform_jreleaser }} ${{ env.ARTIFACT_ID }}-${{ steps.props.outputs.project_version }}-jre-${{ steps.props.outputs.platform_artifact }}.zip
 
       - name: Display structure of downloaded files
         run: ls -R
 
-      # Jlink and Jpackage assembly
-      - name: JReleaser Assemble
-        uses: jreleaser/release-action@v2
-        with:
-          arguments: assemble --select-current-platform --assembler jpackage
-          setup-java: false
-        env:
-          JRELEASER_PROJECT_VERSION: ${{ steps.props.outputs.project_version }}
-          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          JRELEASER_OUTPUT_DIRECTORY: ${{ env.JRELEASER_OUT_DIRECTORY }}
-          JDK_DOWNLOAD_DIRECTORY: ${{ steps.props.outputs.jdk_download_directory }}
-          JDK_VERSION: ${{ steps.props.outputs.jdk_version }}
-          JDK_DISTRO: ${{ steps.props.outputs.jdk_distro }}
-
+      # Jpackage assembly
+      - name: JReleaser JPackage Assemble
+        # The shell is bash on Linux and Powershell in Windows
+        # The quotes are mandatory for Windows otherwise it will see -Djreleaser.select as powershell parameter
+        run: ./mvnw jreleaser:assemble "-Djreleaser.select.current.platform" "-Djreleaser.assemblers=jpackage" --no-transfer-progress --batch-mode
 
       # Upload log
       - name: JReleaser output
@@ -255,10 +228,10 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           retention-days: 1 # 90 by default
-          name: jreleaser-logs-${{env.WORKFLOW_ID}}-${{ steps.props.outputs.project_effective_version }}-${{ steps.props.outputs.platform_artifact }}
+          name: jreleaser-logs-${{env.WORKFLOW_ID}}-${{ steps.props.outputs.project_version }}-${{ steps.props.outputs.platform_artifact }}
           path: |
-            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/trace.log
-            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/output.properties
+            ${{env.BUILD_DIRECTORY}}/jreleaser/trace.log
+            ${{env.BUILD_DIRECTORY}}/jreleaser/output.properties
 
       # Upload Jpackage native package
       # Jlink artifact is not in this upload because we download them into a different directory
@@ -269,8 +242,8 @@ jobs:
           retention-days: 1 # 90 by default
           name: jpackage-${{ steps.props.outputs.project_version }}-${{ steps.props.outputs.platform_artifact }}
           path: |
-            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.pkg
-            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.msi
-            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.deb
-            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.rpm
+            ${{env.BUILD_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.pkg
+            ${{env.BUILD_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.msi
+            ${{env.BUILD_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.deb
+            ${{env.BUILD_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.rpm
 
